### ISSUE TITLE
Static Website Deployment is not active

### ISSUE THREAD

**Issue by SammyOina** [QUALIS-LABS/qualis_static_website#12]
**Describe the bug**
Environment deployment of static website returns error 404

**Comment by 0x6f736f646f** [comment]
@SammyOina Returns a 404 on which action?

**Comment by SammyOina** [comment]
> @SammyOina Returns a 404 on which action?

for the whole site

**Comment by 0x6f736f646f** [comment]
> > @SammyOina Returns a 404 on which action?
> 
> for the whole site

can you show me how the error looks

This is how it looks on my side
![Screenshot from 2020-03-31 00-33-46](https://user-images.githubusercontent.com/28790446/77964186-58bcc700-72e7-11ea-9d0d-5928e9e7deaf.png)

**Comment by SammyOina** [comment]
![issues qualis](https://user-images.githubusercontent.com/44265300/83148284-7056d700-a101-11ea-94ff-21af922cd183.PNG)
@0x6f736f646f  thats what i'm getting

**Comment by 0x6f736f646f** [comment]
@SammyOina Yes we haven't set up the github pages

**Comment by 0x6f736f646f** [comment]
> @SammyOina Yes we haven't set up the github pages
I will push a commit to deploy it

**Comment by 0x6f736f646f** [comment]
https://qualis-labs.github.io/qualis_static_website/Src/index.html

**Comment by 0x6f736f646f** [comment]
I was trying to deploy to GKE but i don't know why it isn't giving me and endpoint

**Comment by 0x6f736f646f** [comment]
This is a cloud run instance 
https://qualisstaticwebsite-q2k3tenogq-uc.a.run.app/

**Comment by 0x6f736f646f** [comment]
@SammyOina 
Finally deployed to cloud run
https://qualisstaticwebsite-q2k3tenogq-uc.a.run.app

**Comment by 0x6f736f646f** [comment]
This is the error for GKE
![Screenshot from 2020-05-29 22-34-53](https://user-images.githubusercontent.com/28790446/83298257-be9cd080-a1fc-11ea-8b36-2f1075277479.png)
It has been like that for 2 days
